#!/bin/bash

if test $(find ../prak02 -type f -name 'bibel.txt' | wc -c) -lt 1
then
    cd ../prak02
    wget http://www.informatik.htw-dresden.de/~robge/bs1/prak/bibel.txt
    cd ../prak04
fi

# Count of word with 3/4 letters
count=$(grep -o "\s\w\{3,3\}\s" ../prak02/bibel.txt | wc -w)
echo "Count of 3 Character Words: $count"

count=$(grep -o "\s\w\{4,4\}\s" ../prak02/bibel.txt | wc -w)
echo "Count of 4 Character Words: $count"

# Amount of different vers beginnings
count=$(grep -o "^\w*\s[0-9]\+:[0-9]\+" ../prak02/bibel.txt | sort | uniq | wc -l)
echo "Amount of different vers beginnings: $count"

# Amount of large written words
count=$(grep -o "\s[A-Z][a-zA-Z]\+\s" ../prak02/bibel.txt | sort | uniq | wc -w)
echo "Amount of large written words: $count"

# All verse with two occurences of the word Löwe
echo "========== Verse mit 2x Löwe =============="
grep "^\(.*\sLöwe\s\)\{2,2\}.*$" ../prak02/bibel.txt
echo "==========================================="

echo "========== Verse mit 3x Löwe =============="
grep "^\(.*\sLöwe\s\)\{3,3\}.*$" ../prak02/bibel.txt
echo "==========================================="

length=0
longest=""
words=$(grep -o "\s[A-Za-z]\{2,\}\s" ../prak02/bibel.txt)
echo "Word count: $(echo "$words" | wc -l)"

for word in $words
do
    cur_length=${#word}
    if [ $cur_length -gt $length ]
    then
        length=$cur_length
        longest=$word
    fi
done
echo "Longest word \"$longest\" from the bibel.txt has $length characters"