#!/bin/bash

add(){
    echo $(($1+$1))
}

sub(){
    echo $(($1-$1))
}

mal(){
    echo $(($1*$2))
}

div(){
    echo $(($1/$2))
}

pow(){
    res=$1
    for ((i=1; i<$2; i++))
    do
        res=$(mal $res $1)
    done
    if test $2 -eq 0
    then
        echo 1
    else
        echo $res
    fi
}

if test $# -ne 3
then 
    echo "Usage: calc num operator num"
    exit 1
fi

num1=$1
operator=$2
num2=$3

case "$operator" in
    +)
        add $num1 $num2
        ;;
    -)
        sub $num1 $num2
        ;;
    \*)
        mal $num1 $num2
        ;;
    /)
        div $num1 $num2
        ;;
    ^)
        pow $num1 $num2
        ;;
    *)
        echo "Invalid operator"
        exit 1
        ;;
esac

exit 0