#!/bin/bash

# if test $# -lt 1
# then
#     echo "Error. Wrong parameter count. Need wcount word"
#     exit 1
# fi

# word=$1
if test $(find ../prak02 -type f -name 'bibel.txt' | wc -c) -lt 1
then
    cd ../prak02
    wget http://www.informatik.htw-dresden.de/~robge/bs1/prak/bibel.txt
    cd ../prak03
fi

while test 1 -eq 1
do
    read word

    if test "$word" == ""
    then
        break
    fi
    count=$(grep -o "\s$word\s" ../prak02/bibel.txt | wc -w)
    echo "$word:$count"

done
exit 0