#!/bin/bash

if test $# -lt 1
then
    echo "Usage: $0 <host>"
    exit 1
fi

ping -c 1 -w 1 $1 >/dev/null 2>/dev/null
if test $? -ne 0
then
    echo "$1 does not answer ping"
    exit 2
fi

ssh s88216@$1 << 'EOF' 
for v in $(who | cut -d " " -f1 | sort | uniq)
do
    n=$(finger $v | grep -o "Name: .*$" | cut -d " " -f2-)
    echo "$v - $n"
done
EOF

exit 0