#!/bin/bash

# a)
echo {a..z}{a..z}{a..z}{a..z}

# b)
echo {{a..z},{A..Z}}{{a..z},{A..Z}}{{a..z},{A..Z}}

# c)
echo isys{101..121}, isys6, isys8, isys{10..29},

# d)

# e) immer b am anfang, darauf folgt enweder ar mit Buchstaben d,n oder k ODER ed und s immer am Ende =>
# bards
# barns
# barks
# beds