#!/bin/bash

size()
{
    size=0
    for num in $(grep "^-" filme.txt | tr -s ' ' | cut -s -d " " -f5);
    do
        size=$((size+num))
    done
    echo $size
}

byteToGiB()
{
    echo $(($1/1024/1024/1024))
}

showSize()
{
    size=$(size)
    echo "Total size of movies (Byte): $size Byte"
    echo "Total size of movies (GiB): $(byteToGiB $size) GiB"
}

moviecol() {
    tr -s ' ' < filme.txt | cut -s -d " " -f9-
}

hist()
{
    echo "Movie Count:Year"
    moviecol | grep -o "([1-2][0-9][0-9][0-9])" | tr -d "()" | sort | uniq -c | sort -nr | tr -s " " | cut -d " " -f2- | tr " " ":"
}

search()
{
    moviecol | rev | cut -d "." -f2- | rev | grep ".*$1.*"
}

ext()
{
    echo "Count:Extension"
    grep -o "\.[a-zA-Z0-9]*$" < filme.txt | cut -s -d "." -f2 | sort | uniq -c | tr -s " " | cut -d " " -f2- | tr " " ":"

    count=$(grep '^d' filme.txt | wc -l)
    echo "Amount of directories: $count"
}

imdb()
{
    ssh ilux150.informatik.htw-dresden.de "grep -P \"\t.*$1.*\t\" /user/profile/active/robge/bs1-tools/title.akas.tsv | cut -f1"
}

syntax()
{
    moviecol | grep -v "^$" | grep -E -v ".*\s\((20[0-2][0-9]|19[0-9][0-9])\)(\..*$|-cd[1-3]\..*$|$)"
}  

missing()
{
    while read -r line
    do
        if test $(search "$line" | wc -w ) -eq 0
        then
            echo  $line
        fi
    done < top100.txt
}

warning()
{
    if test $1 -gt $2
    then
        diff=$(($1-$2))
        echo "Warning: Too many arguments specified. The last $diff argument(s) will be truncated."
    fi
}

if test $# -lt 1
then
    echo "Error: No Method specified. Usage: ./s88216 [search <string> | hist | size | ext | imdb  <string> | syntax | missing]"
    exit 1
fi

if test $1 = "search"
then
    if test $# -lt 2
    then
        echo "Error: Search Parameter missing. Usage: ./s88216 search <search string>"
        exit 1
    fi
    warning $# 2
    search "$2"
elif test $1 = "hist"
then
    warning $# 1
    hist
elif test $1 = "size"
then
    warning $# 1
    showSize
elif test $1 = "ext"
then
    warning $# 1
    ext
elif test $1 = "imdb"
then
    if test $# -lt 2
    then
        echo "Error: Search Parameter missing. Usage: ./s88216 imdb <search string>"
        exit 1
    fi
    warning $# 2
    imdb "$2"
elif test $1 = "syntax"
then
    warning $# 1
    syntax
elif test $1 = "missing"
then
    warning $# 1
    missing
else
    echo "Error: Method not found. Usage: ./s88216 [search <string> | hist | size | ext | imdb <string> | syntax | missing]"
    exit 1
fi